### ISSUE TITLE
Meta (Goal)

### ISSUE THREAD

**Issue by josemiguelvdz** [javics2002/JuegosSerios#11]
La meta será un gameobject, que tendra el mismo ancho que un tile 16x16, que contará con un agujero donde entrará la bola.
La banderá de la meta podrá variar de color dependiendo del número de intentos con los que se supera el nivel. 
Además, al volver a jugar un nivel, la meta tendrá que aparecer del mismo color con el que se supero con el mínimo  número de intentos.
La bandera será de color rojo para los niveles superados, dorada si se ha superado en par o mejor y de platino si se ha hecho hoyo en 1.
El trigger que se encarga de mostrar los resultados se encuentra en el agujero propio de la meta. Cuando la pelota colisione con el trigger, se mostrarán los resultados y se podrá pasar al siguiente nivel.

**Comment by kyranet** [comment]
| normal | gold | platinum |
| :----: | :--: | :------: |
| ![game-flag](https://github.com/javics2002/JuegosSerios/assets/24852502/a4c9c6a9-95a8-478c-81c4-58506f20449e) | ![game-flag-gold](https://github.com/javics2002/JuegosSerios/assets/24852502/868cd7f7-56ca-463f-b4a2-2d76241127a4) | ![game-flag-platinum](https://github.com/javics2002/JuegosSerios/assets/24852502/70431ae6-74c8-4bbb-a1ac-7d9c5048842b) |

**Comment by kyranet** [comment]
Completado con 1a8db78, solo falta las tareas de #15
