### ISSUE TITLE
Seleccion de niveles

### ISSUE THREAD

**Issue by javics2002** [javics2002/JuegosSerios#12]
Desde el menú de selección de niveles podrás elegir el nivel que quieras jugar, aunque los niveles a los que no hayas llegado estarán bloqueados y no serán jugables. Los niveles superados se marcan con una bandera. La bandera es roja para los niveles superados, dorada si se ha superado en par o mejor y de platino si se ha hecho hoyo en 1.
![minigolf level selection](https://github.com/javics2002/JuegosSerios/assets/49459590/d8b66292-0cb8-4ce5-853e-57fc5627ecd9)

**Comment by javics2002** [comment]
Se ha creado el menu de seleccion de niveles instanciando un prefab de nivel. El prefab utiliza los datos del nivel de indice i para saber si esta bloqueado, desbloqueado, completado... y actualizar sus sprites y texto. Si está desbloqueado, al pulsarlo te lleva a ese nivel. Ahora los niveles sacan una captura de si mismos y el menú de seleccion de niveles se actualiza para reflejar los cambios de cada iteracion del proceso de diseño de niveles. Está generalizado para  la variable del Game Manager numberOfLevels.
![image](https://github.com/javics2002/JuegosSerios/assets/49459590/f44bbf2d-e5ec-47b3-89ed-c2cba1e74c88)
Si el nivel esta completado, se marca con la bandera del color correspondiente.
![image](https://github.com/javics2002/JuegosSerios/assets/49459590/f3da6f2a-eda4-4a77-9f1e-66315619b2f7)

**Comment by kyranet** [comment]
| flag-level.png | flag-level-gold.png | flag-level-platinum.png | flag-level-platinum-alt.png |
| :------------: | :-----------------: | :---------------------: | :-------------------------: |
| ![flag-level](https://github.com/javics2002/JuegosSerios/assets/24852502/eeef37ca-0239-4680-bd07-954475b1f511) | ![flag-level-gold](https://github.com/javics2002/JuegosSerios/assets/24852502/8f926def-2331-4931-bf7b-e7d348195fe5) | ![flag-level-platinum](https://github.com/javics2002/JuegosSerios/assets/24852502/cd57b7bc-5e0c-4bee-bcef-47a57270eed1) | ![flag-level-platinum-alt](https://github.com/javics2002/JuegosSerios/assets/24852502/eeeb5215-14a9-4e4b-8576-7797809d96bf) |

**Comment by kyranet** [comment]
En 851ce37 se añadió el fondo nuevo:
![Unity_4XFvGiiciJ](https://github.com/javics2002/JuegosSerios/assets/24852502/5a90a416-97c8-4513-bd9a-fe7a110ce078)

**Comment by kyranet** [comment]
Completado en 1960319:

https://github.com/javics2002/JuegosSerios/assets/24852502/e33819ff-b02f-48c0-a469-40c76e8ac854
