### ISSUE TITLE
Menú principal

### ISSUE THREAD

**Issue by javics2002** [javics2002/JuegosSerios#6]
El juego cuenta con un menú principal, donde podrás ir al menú de selección de nivel y al menú de configuración del juego.
![Minigold main menu](https://github.com/javics2002/JuegosSerios/assets/49459590/512b7e23-0e2b-4c7b-a2b8-017cd31dd486)

**Comment by javics2002** [comment]
El menú principal ya tiene los elementos funcionales
![image](https://github.com/javics2002/JuegosSerios/assets/49459590/31127d42-f9b3-408f-9327-f71f38ceec28)
`public class MainMenu : MonoBehaviour
{
    CanvasGroup mainMenuElements;

	private void Start() {
		mainMenuElements = GetComponentInChildren<CanvasGroup>();
	}

	public void Play() {
        SceneManager.LoadScene("Level Selection");
    }

    public void Settings() {
        mainMenuElements.alpha = 0;
        mainMenuElements.blocksRaycasts = false;
		SceneManager.LoadScene("Settings", LoadSceneMode.Additive);
	}

    public void Exit() {
        Application.Quit();
    }
}`

**Comment by kyranet** [comment]
Completado en 851ce37

![Unity_BzAimvtcR5](https://github.com/javics2002/JuegosSerios/assets/24852502/c0a2a818-da83-471d-a9b6-117774246af8)
