### ISSUE TITLE
Menú de ajustes

### ISSUE THREAD

**Issue by javics2002** [javics2002/JuegosSerios#9]
Desde el menú de configuración del juego podrás modificar las opciones de audio (nivel de sonido, música)
![minigolf settiings](https://github.com/javics2002/JuegosSerios/assets/49459590/0e1f92e4-a300-4666-bf88-00c794a9a72c)

**Comment by javics2002** [comment]
Menú de configuración hecho de manera que se puede llamar desde el menú principal y el juego. Carga los datos del GameManager y los actualiza en el. Al darle a "Save and close" llama a la funcion de guardar del GameManager (por implementar en otra issue).
![image](https://github.com/javics2002/JuegosSerios/assets/49459590/f4b4a298-d091-4622-970d-ef1c97689826)
`
public class Settings : MonoBehaviour
{
	[Header("Audio")]
    public AudioMixer mixer;
	public Slider musicSlider, soundsSlider;

	private void Start() {
		LoadValues();
	}

	public void LoadValues() {
		musicSlider.value = GameManager.Instance.musicVolume;
		soundsSlider.value = GameManager.Instance.soundsVolume;
	}

	public void SaveAndClose() {
        GameManager.Instance.Save();

        SceneManager.UnloadSceneAsync("Settings");
    }

    public void SetMusicVolume(float musicVolume) {
		mixer.SetFloat("musicVol", LinearVolumeToDecibels(musicVolume));
        GameManager.Instance.musicVolume = musicVolume;
	}

    public void SetSoundsVolume(float soundsVolume) {
		mixer.SetFloat("sfxVol", LinearVolumeToDecibels(soundsVolume));
		GameManager.Instance.soundsVolume = soundsVolume;
	}

    float LinearVolumeToDecibels (float linearVolume) {
        return 20 * Mathf.Log10(linearVolume);
	}
}
`

**Comment by kyranet** [comment]
En 851ce37 se añadió el fondo nuevo:
![image](https://github.com/javics2002/JuegosSerios/assets/24852502/3579c8b8-23bf-4657-997a-69fec9aa729f)

Pendiente reescribir la UI a UI Toolkit además de integrar todos los elementos que faltan.

**Comment by kyranet** [comment]
Casi terminado en 25de5dc, falta estilizar los hovers del dropdown:
![MiniGolf_N8K6uUnAHk](https://github.com/javics2002/JuegosSerios/assets/24852502/975009c4-4ee0-44f5-9fd4-bdc56b8da5fd)

**Comment by kyranet** [comment]
Diseño terminado en 9ed1ddf, introduciendo cambios estilísticos y un elemento para previsualizar el color:
https://github.com/javics2002/JuegosSerios/assets/24852502/ea93878d-9948-4c7d-a380-fd7fd67de0e4

**Comment by javics2002** [comment]
Ahora no se puede interactuar con el juego mientras estén los ajustes abiertos, y tampoco se pueden abrir multiples menús de configuración
